version: 2.1

# このプロジェクトで実行するジョブの定義
jobs:
  build:
    docker:
      - image: docker:19.03.8
        auth:
          username: suwa33
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数の参照
    steps:
      - checkout
      - run: echo "this is the build job"
  get_token:
    docker:
      - image: docker:19.03.8
        auth:
          username: suwa33
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数の参照
    steps:
      - checkout
      - run: apk add curl
      - run: git clone git@github.com:Ishizuka427/ca_web.git
    #  - run: ブランチの作成
    #  - run: yamlの内容を書き換える
      - run: |
          curl -v -H "Authorization: token $TOKEN" https://api.github.com/repos/$OWNER/$REPO/pulls --data '{
          "title": "Amazing new feature",
          "body": "Please pull these awesome changes in!",
          "head": "'Ishizuka427:docker-image-update'",
          "base": "'$BASE'"
          }'
# ジョブの実行順の指定
workflows:
  build_and_test:
    jobs:
      - build
      - get_token